name: CD to Staging
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on : ubuntu-latest
        steps:
            - name: Setup SSH key
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/private_key
                chmod 600 ~/.ssh/private_key

            - name: Deploy on server
              run: |
                ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key ubuntu@65.0.109.27 << 'EOF'
                cd /BMS/
                git pull origin main
                pnpm install
                pnpm run build
                pm2 restart all
                EOF