name: CD to Staging
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on : ubuntu-latest
        steps:
            - name: Setup SSH key
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/private_key
                chmod 600 ~/.ssh/private_key
                echo ~/.ssh/private_key

            - name: Deploy on server
              run: |
                echo yes | ssh -i ~/.ssh/private_key ubuntu@65.0.109.27 << 'EOF'
                echo "Deploying to staging server..."
                cd bms/
                git pull origin master
                pnpm install
                pnpm run build
                pm2 restart all
                EOF